export const CITY_NAMES = [
  'Ashford',
  'Brindle',
  'Coalport',
  'Dunmore',
  'Eastvale',
  'Fernhill',
  'Grayton',
  'Hartwell',
  'Ironbridge',
  'Junction City',
  'Kestrel Falls',
  'Larkspur',
  'Millbrook',
  'Northgate',
  'Oakhaven',
  'Pinecrest',
  'Quarry Bend',
  'Redwater',
  'Silverton',
  'Thornbury',
  'Umberfield',
  'Violet Hollow',
  'Westmere',
  'Yarrow',
  'Zephyr Point',
  'Bellweather',
  'Cinder Gap',
  'Dovetail',
  'Emberton',
  'Foxglove',
] as const
